[build]
  command = "ng build --configuration production && ng run go-quiz:serverless:production"
  publish = "dist/go-quiz/browser"
  targetPort = "4200"
[[plugins]]
  package = "@netlify/plugin-angular-universal"